// <auto-generated />
namespace Gdn.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddWeChatAccount : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddWeChatAccount));
        
        string IMigrationMetadata.Id
        {
            get { return "201705080003099_AddWeChatAccount"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
